### ISSUE TITLE
在 php artisan migrate 發生錯誤 (sqlite)

### ISSUE THREAD

**Issue by rc1021** [jhabc1314/management#1]
$ php artisan migrate
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.02 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.02 seconds)
Migrating: 2019_06_26_082215_create_management_server_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1 near "comment": syntax error (SQL: ALTER TABLE `management_server` comment '服务信息表')

  >  at /blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
    669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1 near "comment": syntax error")
      /blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php:457

  2   PDO::prepare()
      /blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php:457

**Comment by jhabc1314** [comment]
抱歉，一直看到消息 😁

这个是在migration的时候增加表的注释，可以看下mysql版本是否支持，也可以直接将`management/migrations/2019_06_26_082215_create_management_server_table.php ` 第27行注释掉
